##开发环境配置文件
server:
  port: 8082
person:
  name: 开发
  age: 27
  ##配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_person
    username: root
    password: password
    ##配置jpa信息
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    ##redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
    ##连接池中的最大空闲连接数
      max-idle: 20
      ##连接池中的最小空闲连接数
      min-idle: 1
      ##连接池最大连接数(使用负值表示没有限制)
      max-active: 20
      ##连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: 1
      ##默认是索引为0的数据库
    database: 0
    ##连接超时时间(毫秒)
    timeout: 0
    ##http配置
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
