##生产环境配置文件
server:
  port: 8083
person:
  age: 28
  name: 生产
    ##http配置
http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true